export const PROPERTIES_DATA = [
  {
    id: 1,
    title: 'House #1',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 2,
    title: 'House #2',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 3,
    title: 'House #3',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 4,
    title: 'House #4',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 1,
    title: 'House #1',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 2,
    title: 'House #2',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 3,
    title: 'House #3',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 4,
    title: 'House #4',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 1,
    title: 'House #1',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 2,
    title: 'House #2',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 3,
    title: 'House #3',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 4,
    title: 'House #4',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 1,
    title: 'House #1',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 2,
    title: 'House #2',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 3,
    title: 'House #3',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 4,
    title: 'House #4',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 1,
    title: 'House #1',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 2,
    title: 'House #2',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 3,
    title: 'House #3',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
  {
    id: 4,
    title: 'House #4',
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    date: '2023-11-22T14:29:32Z',
    dateWords: '1 day ago',
    agent: 1,
    user: 1,
    new: true,
    featured: true,
    categories: [1, 2],
    amenities: [11, 12, 13, 14, 5],
    sliderImages: [
      '/images/slider/apartments.svg',
      '/images/slider/houses.svg',
      '/images/slider/commercial.svg',
    ],
    propertyData: {
      agentPrice: '1.2 Crore',
      propertyDemand: '1.5 Crore',
      propertyPriceUnit: '1.5 Crore',
      propertyArea: '1080',
      propertyAreaUnit: 'sq.ft',
      propertyType: 'Houses',
      subPropertyType: 'topFloor',
      propertyDirection: 'East Open',
      propertyLocation: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        area: 'Gulistan e johar',
        city: 'Karachi',
      },
    },
    propertyStats: {
      areaSize: 'Large',
      range: '1000000',
      installment: 'Available',
      readyFor: 'Possession',
    },
    propertyImages: [
      '/images/proposals/images/proposalImage1.png',
      '/images/proposals/images/proposalImage2.png',
      '/images/proposals/images/proposalImage3.png',
      '/images/proposals/images/proposalImage4.png',
      '/images/proposals/images/proposalImage5.png',
      '/images/proposals/images/proposalImage6.png',
    ],
    propertyVideos: [
      '/images/proposals/videos/proposalVideo1.png',
      '/images/proposals/videos/proposalVideo2.png',
      '/images/proposals/videos/proposalVideo3.png',
      '/images/proposals/videos/proposalVideo4.png',
      '/images/proposals/videos/proposalVideo5.png',
      '/images/proposals/videos/proposalVideo6.png',
    ],
    propertyOverview: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      unit: 'PKR',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
  },
];
export const PROPERTIES_CATEGORIES = [
  {
    id: 1,
    image: '/images/categories/category1.svg',
    name: 'Category 1',
    link: '/',
  },
  {
    id: 2,
    image: '/images/categories/category2.svg',
    name: 'Category 2',
    link: '/',
  },
  {
    id: 3,
    image: '/images/categories/category3.svg',
    name: 'Category 3',
    link: '/',
  },
  {
    id: 4,
    image: '/images/categories/category4.svg',
    name: 'Category 4',
    link: '/',
  },
  {
    id: 5,
    image: '/images/categories/category5.svg',
    name: 'Category 5',
    link: '/',
  },
  {
    id: 6,
    image: '/images/categories/category6.svg',
    name: 'Category 6',
    link: '/',
  },
  {
    id: 7,
    image: '/images/categories/category7.svg',
    name: 'Category 7',
    link: '/',
  },
  {
    id: 8,
    image: '/images/categories/category8.svg',
    name: 'Category 8',
    link: '/',
  },
];
export const PROPERTIES_AMENITIES = [
  {
    id: 1,
    title: 'Bedrooms',
    name: 'bedrooms',
    icon: '/images/amenities/bedrooms.svg',
    link: '/',
  },
  {
    id: 2,
    title: 'Bathrooms',
    name: 'bathrooms',
    icon: '/images/amenities/bathrooms.svg',
    link: '/',
  },
  {
    id: 3,
    title: 'Parking',
    name: 'parking',
    icon: '/images/amenities/parking.svg',
    link: '/',
  },
  {
    id: 4,
    title: 'Swimming pool',
    name: 'swimming-pool',
    icon: '/images/amenities/swimming-pool.svg',
    link: '/',
  },
  {
    id: 5,
    title: 'Washing area',
    name: 'washing-area',
    icon: '/images/amenities/washing-area.svg',
    link: '/',
  },
  {
    id: 6,
    title: 'Masjid',
    name: 'masjid',
    icon: '/images/amenities/masjid.svg',
    link: '/',
  },
  {
    id: 7,
    title: 'Fitness center',
    name: 'fitness-center',
    icon: '/images/amenities/fitness-center.svg',
    link: '/',
  },
  {
    id: 8,
    title: 'Hour Electricity',
    name: 'hour-electricity',
    icon: '/images/amenities/hour-electricity.svg',
    link: '/',
  },
  {
    id: 9,
    title: 'Corridor',
    name: 'corridor',
    icon: '/images/amenities/corridor.svg',
    link: '/',
  },
  {
    id: 10,
    title: 'Clubhouse',
    name: 'clubhouse',
    icon: '/images/amenities/clubhouse.svg',
    link: '/',
  },
  {
    id: 11,
    title: 'R.O Plant',
    name: 'ro-plant',
    icon: '/images/amenities/r.o-plant.svg',
    link: '/',
  },
  {
    id: 12,
    title: 'Auto Generator',
    name: 'auto-generator',
    icon: '/images/amenities/auto-generator.svg',
    link: '/',
  },
  {
    id: 13,
    title: 'Playground',
    name: 'playground',
    icon: '/images/amenities/playground.svg',
    link: '/',
  },
  {
    id: 14,
    title: 'Servant Area',
    name: 'servant-area',
    icon: '/images/amenities/servant-area.svg',
    link: '/',
  },
  {
    id: 15,
    title: 'Complete Boundary Wall',
    name: 'complete-boundary-wall',
    icon: '/images/amenities/complete-boundary-wall.svg',
    link: '/',
  },
  {
    id: 16,
    title: 'Senior citizen area',
    name: 'senior-citizen-area',
    icon: '/images/amenities/senior-citizen-area.svg',
    link: '/',
  },
  {
    id: 17,
    title: 'Basketball courts',
    name: 'basketball-courts',
    icon: '/images/amenities/basketball-courts.svg',
    link: '/',
  },
  {
    id: 18,
    title: 'Huge Park',
    name: 'huge-park',
    icon: '/images/amenities/huge-park.svg',
    link: '/',
  },
  {
    id: 19,
    title: 'Utility Store',
    name: 'utility-store',
    icon: '/images/amenities/utility-store.svg',
    link: '/',
  },
  {
    id: 20,
    title: 'Walking trails',
    name: 'walking-trails',
    icon: '/images/amenities/walking-trails.svg',
    link: '/',
  },
  {
    id: 21,
    title: 'Concierge services',
    name: 'concierge-services',
    icon: '/images/amenities/concierge-services.svg',
    link: '/',
  },
  {
    id: 22,
    title: 'Rooftop terrace',
    name: 'rooftop-terrace',
    icon: '/images/amenities/rooftop-terrace.svg',
    link: '/',
  },
  {
    id: 23,
    title: 'Pet-friendly facilities',
    name: 'pet-friendly-facilities',
    icon: '/images/amenities/pet-friendly-facilities.svg',
    link: '/',
  },
  {
    id: 24,
    title: 'On-site maintenance',
    name: 'on-site-maintenance',
    icon: '/images/amenities/on-site-maintenance.svg',
    link: '/',
  },
  {
    id: 25,
    title: 'Business centre',
    name: 'business-centre',
    icon: '/images/amenities/business-centre.svg',
    link: '/',
  },
  {
    id: 26,
    title: '24/7 security',
    name: '24/7-security',
    icon: '/images/amenities/24/7-security.svg',
    link: '/',
  },
];
// reduce Data lenght for efficey prpouse
//Reason: to much data (from 200 lines to 20)
export const POPULAR_LOCATIONS_DATA = {
  title: 'Popular Locations',
  description:
    'To browse & buy in your areas of interest. Look of properties by category',
  listingType: ['Sell', 'Rent'],
  property_types: [
    'Houses',
    'Flats',
    'Plots',
    'Farm Houses',
    'Shops',
    'Offices',
  ],
  locations: [
    'Karachi',
    'Lahore',
    'Islamabad',
    'Rawalpindi',
    'Faislabad',
    'Abbottabad',
    'Multan',
    'Heydrabad',
    'Peshawar',
    'Sargodha',
  ],
};

export const ADD_PROPERTY = [
  {
    id: 1, //id
    propertyTitle: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
    propertyDescription:
      'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
    userid: 1, // current user ID
    agentid: null,
    adStatus: 'published', // draft or published //text
    locationPurpose: {
      adPurpose: 'sell', // sell or rent //text
      propertyType: 'House', // house, plots, commercial, //text
      propetySubType: 'Flat', //text
      // address:'401/B, Blossom Trade Center',
      // location: 'Gulistan e Johar',
      geolocation: '', //text
    },
    sizeBudgets: {
      propertyArea: {
        area: 121, //number
        unit: 'sqft', //text
      },
      propertyAmount: {
        area: 121, //number
        unit: 'sqft', //text
      },
      instalmentAvailable: true, //bolean
      readyPossession: true, //bolean
    },
    featureAmenities: [
      // Array object
      { id: 1, name: 'Bedrooms', count: 3 },
      { id: 2, name: 'BathRooms', count: 3 },
      { id: 3, name: 'Parking', count: 3 },
      // ...
    ],
    media: {
      //object Array
      images: ['imagesrc1', 'imagesrc2', 'imagesrc3', 'imagesrc4', 'imagesrc5'], //array
      videos: ['videosrc1', 'videosrc2', 'videosrc3', 'videosrc4', 'videosrc5'], //array
    },
  },
];
