import { createSlice } from '@reduxjs/toolkit';

const postlistingAdSlice = createSlice({
  name: 'PostlistingAdSlice',
  initialState: {
    agentPostings: [
      {
        property_id: 1,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 2,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 3,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 4,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Plots',
        propertyType: 'Plots',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 5,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Plots',
        propertyType: 'Plots',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 6,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Plots',
        propertyType: 'Plots',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 7,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Commercials',
        propertyType: 'Commercials',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 8,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Commercials',
        propertyType: 'Commercials',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 9,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Commercials',
        propertyType: 'Commercials',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 10,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Rent',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 11,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Rent',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 12,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Rent',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 13,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Rent',
        propertyCategory: 'Plots',
        propertyType: 'Plots',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 14,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Rent',
        propertyCategory: 'Plots',
        propertyType: 'Plots',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 15,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Rent',
        propertyCategory: 'Plots',
        propertyType: 'Plots',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 16,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Rent',
        propertyCategory: 'Commercials',
        propertyType: 'Commercials',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 17,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Rent',
        propertyCategory: 'Commercials',
        propertyType: 'Commercials',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 18,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Rent',
        propertyCategory: 'Commercials',
        propertyType: 'Commercials',
        instalmentAvailable: false,
        readyPossession: false,
      },
    ],
    active: [
      {
        property_id: 1,
        user_id: 21,
        status: 'connected',
        images: [],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Plots',
        propertyType: 'Plots',
        instalmentAvailable: false,
        readyPossession: false,
      },
    ],
    draft: [
      {
        property_id: 1,
        user_id: 21,
        status: 'draft',
        images: [],
        videos: [],
        title: 'My First Ad',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        area: 650,
        amount: 70000,
        areaUnit: 'sq.m',
        amountCurrency: 'SAR',
        city: 'Lahore',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Plots',
        propertyType: 'Plots',
        instalmentAvailable: false,
        readyPossession: false,
      },
    ],
    featuredPostings: [
      {
        property_id: 1,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          './images/features/feature1.png',
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'Index Industrial Park',
        location: 'Hub River Road',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: '3.0 Crore',
        areaUnit: 'sq.m',
        amountCurrency: 'PKR',
        city: 'Islamabad',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 2,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          './images/features/feature2.png',
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'Index Industrial Park',
        location: 'Hub River Road',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: '3.0 Crore',
        areaUnit: 'sq.m',
        amountCurrency: 'PKR',
        city: 'Islamabad',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 3,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          './images/features/feature3.png',
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'Index Industrial Park',
        location: 'Hub River Road',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: '3.0 Crore',
        areaUnit: 'sq.m',
        amountCurrency: 'PKR',
        city: 'Islamabad',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 4,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          './images/features/feature4.png',
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'Index Industrial Park',
        location: 'Hub River Road',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: '3.0 Crore',
        areaUnit: 'sq.m',
        amountCurrency: 'PKR',
        city: 'Islamabad',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Plots',
        propertyType: 'Plots',
        instalmentAvailable: false,
        readyPossession: false,
      },
    ],
    newPostings: [
      {
        property_id: 1,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: '1.5 Crore',
        areaUnit: 'sq.m',
        amountCurrency: 'PKR',
        city: 'Karachi',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 2,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: '1.5 Crore',
        areaUnit: 'sq.m',
        amountCurrency: 'PKR',
        city: 'Karachi',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 3,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: '1.5 Crore',
        areaUnit: 'sq.m',
        amountCurrency: 'PKR',
        city: 'Karachi',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 4,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: '1.5 Crore',
        areaUnit: 'sq.m',
        amountCurrency: 'PKR',
        city: 'Karachi',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Plots',
        propertyType: 'Plots',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 5,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: '1.5 Crore',
        areaUnit: 'sq.m',
        amountCurrency: 'PKR',
        city: 'Karachi',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 6,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: '1.5 Crore',
        areaUnit: 'sq.m',
        amountCurrency: 'PKR',
        city: 'Karachi',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 7,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: '1.5 Crore',
        areaUnit: 'sq.m',
        amountCurrency: 'PKR',
        city: 'Karachi',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Houses',
        propertyType: 'Houses',
        instalmentAvailable: false,
        readyPossession: false,
      },
      {
        property_id: 8,
        user_id: 21,
        status: 'submit',
        other_features: [
          'Park',
          'Masjid',
          'Playground',
          '24 Hours CCTV Security System',
          '24 Hours Water Supply',
        ],
        images: [
          `/images/properties/PropertyCardImageHouse.png`,
          '/images/slider/apartments.svg',
          '/images/slider/houses.svg',
          '/images/slider/commercial.svg',
        ],
        videos: [],
        title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
        location: 'gulshan',
        orientation: 'East Open',
        description:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        geo_location:
          'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14472.341891430968!2d67.115604!3d24.929158!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33feab1c28595%3A0xa3b2a5dc2f97a82e!2seSpark%20Consulting%20Group!5e0!3m2!1sen!2s!4v1709901100906!5m2!1sen!2s',
        area: 650,
        amount: '1.5 Crore',
        areaUnit: 'sq.m',
        amountCurrency: 'PKR',
        city: 'Karachi',
        bedrooms: 2,
        connects: '',
        bathrooms: 2,
        parking: 1,
        clubhouse: 1,
        swimming_pool: 1,
        fitness_center: 1,
        playground: 1,
        servant_area: 1,
        utility_store: 1,
        rooftop_terrace: 1,
        on_site_maintenance: 1,
        washing_area: 1,
        hour_electricity: 1,
        auto_generator: 1,
        complete_boundary_wall: 1,
        walking_trails: 1,
        pet_friendly_facilities: 1,
        security: 1,
        masjid: 1,
        corridor: 1,
        r_o_plant: 1,
        basketball_courts: 1,
        huge_park: 1,
        concierge_services: 1,
        business_centre: 1,
        purpose: 'Sell',
        propertyCategory: 'Plots',
        propertyType: 'Plots',
        instalmentAvailable: false,
        readyPossession: false,
      },
    ],
    poposalIdentify: [],
    trash: [],
    save: [],
    proposalsTrash: [],
    addAmenities: [],
    checkedAmenities: [],
  },
  reducers: {
    handleAdaminities: (state, action) => {
      state.addAmenities = action.payload;
    },
    toggleCheckAmenityClear: (state) => {
      state.addAmenities = [];
      state.checkedAmenities = [];
    },
    handlePostlistingAd: (state, action) => {
      const newAd = action.payload;
      const existingAdIndex = state?.agentPostings?.findIndex(
        (ad) => ad?.property_id === newAd?.property_id
      );
      if (existingAdIndex !== -1) {
        state.agentPostings[existingAdIndex] = newAd;
      } else {
        state?.agentPostings?.push(newAd);
      }
    },
    handleSubmitDraftForAgent: (state, action) => {
      const newDraft = action.payload;
      const existingDraftIndex = state?.draft?.findIndex(
        (draft) => draft?.property_id === newDraft?.property_id
      );
      if (existingDraftIndex !== -1) {
        state.draft[existingDraftIndex] = newDraft;
      } else {
        state?.draft?.push(newDraft);
      }
    },
    handleAgentTrash: (state, action) => {
      const { property_id, currentTab } = action.payload;
      console.log(state, 'state');
      // all
      const postingsIndex = state?.agentPostings?.findIndex(
        (ad) => ad?.property_id === property_id
      );
      if (postingsIndex !== -1 && currentTab == 'All') {
        const postings_trash = state?.agentPostings?.splice(
          postingsIndex,
          1
        )[0];
        state.trash.push(postings_trash);
      }
      // Active
      const activeIndex = state?.active?.findIndex(
        (ad) => ad?.property_id === property_id
      );
      if (activeIndex !== -1 && currentTab == 'Active') {
        const active_trash = state?.active?.splice(activeIndex, 1)[0];
        state?.trash?.push(active_trash);
      }
      const draftIndex = state?.draft?.findIndex(
        (ad) => ad?.property_id === property_id
      );
      if (draftIndex !== -1 && currentTab == 'Draft') {
        const draft_trash = state?.draft?.splice(draftIndex, 1)[0];
        state?.trash?.push(draft_trash);
      }
    },

    handleSaveRequest: (state, action) => {
      const { post, userId } = action.payload;
      const foundObject = state?.save?.find(
        (obj) =>
          obj?.user_id === userId && obj?.property_id === post.property_id
      );
      if (!foundObject) {
        state?.save?.push({ user_id: userId, property_id: post.property_id });
      }
    },

    handleTrashProposal: (state, action) => {
      const { property_id, currentTab } = action.payload;
      // save
      const saveIndex = state?.save?.findIndex(
        (ad) => ad?.property_id === property_id
      );
      if (saveIndex !== -1 && currentTab == 'Save Request') {
        const postings_trash = state?.save?.splice(saveIndex, 1)[0];
        state.proposalsTrash.push(postings_trash);
      }
      // active
      const active_proposal = state?.activeProposals?.findIndex(
        (ad) => ad?.property_id === property_id
      );
      if (active_proposal !== -1 && currentTab == 'Active') {
        console.log(active_proposal, 'active_proposal');
        const postings_trash = state?.activeProposals?.splice(
          active_proposal,
          2
        )[0];
        state.proposalsTrash.push(postings_trash);
      }
    },
    handleIndentifier: (state, action) => {
      state?.poposalIdentify?.push(action.payload);
    },
  },
});

export const {
  handlePostlistingAd,
  handleSubmitDraftForAgent,
  handleAgentTrash,
  handleIndentifier,
  handleTrashProposal,
  handleSaveRequest,
  handleAdaminities,
  toggleCheckAmenityClear,
} = postlistingAdSlice.actions;
export default postlistingAdSlice.reducer;
