export const PATH = {
  home: '/',
  dashboard: '/dashboard',
  buyProduct: '/dashboard/prop-shop/buy-product',
  liveBidding: '/dashboard/live-bidding',
  biddings: '/dashboard/biddings',
  notFound: '/_not-found',
  about: '/about',
  agentProfile: '/agent-profile',
  agent: '/agents',
  blogs: '/blogs',
  careers: '/careers',
  contactUs: '/contact-us',
  agentPrefernce: '/dashboard/agent-settings/preferences',
  liceBuddings: '/dashboard/live-bidding',
  proposals: '/dashboard/proposals',
  faqs: '/faqs',
  jagah: '/jagah360',
  pricePlans: '/price-plan',
  privacyPolicy: '/privacy-policy',
  projects: '/project ',
  properties: '/properties',
  sellRentForMe: '/sell-rent-for-me',
  signIn: '/signin',
  signUp: '/signup',
  termsConditions: '/terms-conditions',
  users: '/users',
};
