export const PROPERTIES_LISTING = [
  {
    id: 1,
    agent: 1,
    Propertytitle: 'House #1',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    postedDate: '1 day ago',
    propertyData: {
      propertyPrice: '1.2 Crore',
      propertyDemand: '1 Crore 50 Lac',
      area: '1080 sq.ft',
      title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
      description:
        'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
      type: 'Houses',
      direction: 'East Open',
      location: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        city: 'Karachi',
      },
      amenities: [
        'Park',
        'Masjid',
        'Playground',
        '24 Hours CCTV Security System',
        '24 Hours Water Supply',
      ],
    },
    agentData: {
      id: 1,
      price: '1.5 Crore',
      profileimage: '/images/agent-profile/profileimage.svg',
      name: 'Arman Khan',
      agentDescription:
        'It was popularised in the 1960s with the release of Letraset sheets containing Lorem',
      profileLink: '/agents/1',
      chatLink: '/chat/agent/1',
    },
    propertyDetails: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
    sliderImages: [
      '/images/slider/apartments.jpg',
      '/images/slider/houses.jpg',
      '/images/slider/commercial.jpg',
    ],
  },
  {
    id: 2,
    Propertytitle: 'Plot #1',
    coverImage: '/images/properties/PropertyCardImagePlots.jpeg',
    postedDate: '1 day ago',
    propertyData: {
      propertyPrice: '1.2 Crore',
      propertyDemand: '1 Crore 50 Lac',
      area: '1080 sq.ft',
      title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
      description:
        'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
      type: 'Plots',
      direction: 'East Open',
      location: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        city: 'Karachi',
      },
      amenities: [
        'Park',
        'Masjid',
        'Playground',
        '24 Hours CCTV Security System',
        '24 Hours Water Supply',
      ],
    },
    agentData: {
      id: 1,
      price: '1.5 Crore',
      profileimage: '/images/agent-profile/profileimage.svg',
      name: 'Arman Khan',
      agentDescription:
        'It was popularised in the 1960s with the release of Letraset sheets containing Lorem',
      profileLink: '/agents/1',
      chatLink: '/chat/agent/1',
    },
    propertyDetails: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
    sliderImages: [
      '/images/slider/apartments.jpg',
      '/images/slider/houses.jpg',
      '/images/slider/commercial.jpg',
    ],
  },
  {
    id: 3,
    Propertytitle: 'Comemrcial #1',
    coverImage: '/images/properties/PropertyCardImageCommercial.jpeg',
    postedDate: '1 day ago',
    propertyData: {
      propertyPrice: '1.2 Crore',
      propertyDemand: '1 Crore 50 Lac',
      area: '1080 sq.ft',
      title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
      description:
        'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
      type: 'Commercial',
      direction: 'East Open',
      location: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        city: 'Karachi',
      },
      amenities: [
        'Park',
        'Masjid',
        'Playground',
        '24 Hours CCTV Security System',
        '24 Hours Water Supply',
      ],
    },
    agentData: {
      id: 1,
      price: '1.5 Crore',
      profileimage: '/images/agent-profile/profileimage.svg',
      name: 'Arman Khan',
      agentDescription:
        'It was popularised in the 1960s with the release of Letraset sheets containing Lorem',
      profileLink: '/agents/1',
      chatLink: '/chat/agent/1',
    },
    propertyDetails: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
    sliderImages: [
      '/images/slider/apartments.jpg',
      '/images/slider/houses.jpg',
      '/images/slider/commercial.jpg',
    ],
  },
  {
    id: 1,
    Propertytitle: 'House #1',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    postedDate: '1 day ago',
    propertyData: {
      propertyPrice: '1.2 Crore',
      propertyDemand: '1 Crore 50 Lac',
      area: '1080 sq.ft',
      title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
      description:
        'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
      type: 'Houses',
      direction: 'East Open',
      location: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        city: 'Karachi',
      },
      amenities: [
        'Park',
        'Masjid',
        'Playground',
        '24 Hours CCTV Security System',
        '24 Hours Water Supply',
      ],
    },
    agentData: {
      id: 1,
      price: '1.5 Crore',
      profileimage: '/images/agent-profile/profileimage.svg',
      name: 'Arman Khan',
      agentDescription:
        'It was popularised in the 1960s with the release of Letraset sheets containing Lorem',
      profileLink: '/agents/1',
      chatLink: '/chat/agent/1',
    },
    propertyDetails: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
    sliderImages: [
      '/images/slider/apartments.jpg',
      '/images/slider/houses.jpg',
      '/images/slider/commercial.jpg',
    ],
  },
  {
    id: 2,
    Propertytitle: 'Plot #1',
    coverImage: '/images/properties/PropertyCardImagePlots.jpeg',
    postedDate: '1 day ago',
    propertyData: {
      propertyPrice: '1.2 Crore',
      propertyDemand: '1 Crore 50 Lac',
      area: '1080 sq.ft',
      title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
      description:
        'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
      type: 'Plots',
      direction: 'East Open',
      location: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        city: 'Karachi',
      },
      amenities: [
        'Park',
        'Masjid',
        'Playground',
        '24 Hours CCTV Security System',
        '24 Hours Water Supply',
      ],
    },
    agentData: {
      id: 1,
      price: '1.5 Crore',
      profileimage: '/images/agent-profile/profileimage.svg',
      name: 'Arman Khan',
      agentDescription:
        'It was popularised in the 1960s with the release of Letraset sheets containing Lorem',
      profileLink: '/agents/1',
      chatLink: '/chat/agent/1',
    },
    propertyDetails: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
    sliderImages: [
      '/images/slider/apartments.jpg',
      '/images/slider/houses.jpg',
      '/images/slider/commercial.jpg',
    ],
  },
  {
    id: 3,
    Propertytitle: 'Comemrcial #1',
    coverImage: '/images/properties/PropertyCardImageCommercial.jpeg',
    postedDate: '1 day ago',
    propertyData: {
      propertyPrice: '1.2 Crore',
      propertyDemand: '1 Crore 50 Lac',
      area: '1080 sq.ft',
      title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
      description:
        'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
      type: 'Commercial',
      direction: 'East Open',
      location: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        city: 'Karachi',
      },
      amenities: [
        'Park',
        'Masjid',
        'Playground',
        '24 Hours CCTV Security System',
        '24 Hours Water Supply',
      ],
    },
    agentData: {
      id: 1,
      price: '1.5 Crore',
      profileimage: '/images/agent-profile/profileimage.svg',
      name: 'Arman Khan',
      agentDescription:
        'It was popularised in the 1960s with the release of Letraset sheets containing Lorem',
      profileLink: '/agents/1',
      chatLink: '/chat/agent/1',
    },
    propertyDetails: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
    sliderImages: [
      '/images/slider/apartments.jpg',
      '/images/slider/houses.jpg',
      '/images/slider/commercial.jpg',
    ],
  },
  {
    id: 1,
    Propertytitle: 'House #1',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    postedDate: '1 day ago',
    propertyData: {
      propertyPrice: '1.2 Crore',
      propertyDemand: '1 Crore 50 Lac',
      area: '1080 sq.ft',
      title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
      description:
        'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
      type: 'Houses',
      direction: 'East Open',
      location: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        city: 'Karachi',
      },
      amenities: [
        'Park',
        'Masjid',
        'Playground',
        '24 Hours CCTV Security System',
        '24 Hours Water Supply',
      ],
    },
    agentData: {
      id: 1,
      price: '1.5 Crore',
      profileimage: '/images/agent-profile/profileimage.svg',
      name: 'Arman Khan',
      agentDescription:
        'It was popularised in the 1960s with the release of Letraset sheets containing Lorem',
      profileLink: '/agents/1',
      chatLink: '/chat/agent/1',
    },
    propertyDetails: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
    sliderImages: [
      '/images/slider/apartments.jpg',
      '/images/slider/houses.jpg',
      '/images/slider/commercial.jpg',
    ],
  },
  {
    id: 2,
    Propertytitle: 'Plot #1',
    coverImage: '/images/properties/PropertyCardImagePlots.jpeg',
    postedDate: '1 day ago',
    propertyData: {
      propertyPrice: '1.2 Crore',
      propertyDemand: '1 Crore 50 Lac',
      area: '1080 sq.ft',
      title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
      description:
        'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
      type: 'Plots',
      direction: 'East Open',
      location: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        city: 'Karachi',
      },
      amenities: [
        'Park',
        'Masjid',
        'Playground',
        '24 Hours CCTV Security System',
        '24 Hours Water Supply',
      ],
    },
    agentData: {
      id: 1,
      price: '1.5 Crore',
      profileimage: '/images/agent-profile/profileimage.svg',
      name: 'Arman Khan',
      agentDescription:
        'It was popularised in the 1960s with the release of Letraset sheets containing Lorem',
      profileLink: '/agents/1',
      chatLink: '/chat/agent/1',
    },
    propertyDetails: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
    sliderImages: [
      '/images/slider/apartments.jpg',
      '/images/slider/houses.jpg',
      '/images/slider/commercial.jpg',
    ],
  },
  {
    id: 3,
    Propertytitle: 'Comemrcial #1',
    coverImage: '/images/properties/PropertyCardImageCommercial.jpeg',
    postedDate: '1 day ago',
    propertyData: {
      propertyPrice: '1.2 Crore',
      propertyDemand: '1 Crore 50 Lac',
      area: '1080 sq.ft',
      title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
      description:
        'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
      type: 'Commercial',
      direction: 'East Open',
      location: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        city: 'Karachi',
      },
      amenities: [
        'Park',
        'Masjid',
        'Playground',
        '24 Hours CCTV Security System',
        '24 Hours Water Supply',
      ],
    },
    agentData: {
      id: 1,
      price: '1.5 Crore',
      profileimage: '/images/agent-profile/profileimage.svg',
      name: 'Arman Khan',
      agentDescription:
        'It was popularised in the 1960s with the release of Letraset sheets containing Lorem',
      profileLink: '/agents/1',
      chatLink: '/chat/agent/1',
    },
    propertyDetails: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
    sliderImages: [
      '/images/slider/apartments.jpg',
      '/images/slider/houses.jpg',
      '/images/slider/commercial.jpg',
    ],
  },
  {
    id: 1,
    Propertytitle: 'House #1',
    coverImage: '/images/properties/PropertyCardImageHouse.png',
    postedDate: '1 day ago',
    propertyData: {
      propertyPrice: '1.2 Crore',
      propertyDemand: '1 Crore 50 Lac',
      area: '1080 sq.ft',
      title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
      description:
        'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
      type: 'Houses',
      direction: 'East Open',
      location: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        city: 'Karachi',
      },
      amenities: [
        'Park',
        'Masjid',
        'Playground',
        '24 Hours CCTV Security System',
        '24 Hours Water Supply',
      ],
    },
    agentData: {
      id: 1,
      price: '1.5 Crore',
      profileimage: '/images/agent-profile/profileimage.svg',
      name: 'Arman Khan',
      agentDescription:
        'It was popularised in the 1960s with the release of Letraset sheets containing Lorem',
      profileLink: '/agents/1',
      chatLink: '/chat/agent/1',
    },
    propertyDetails: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
    sliderImages: [
      '/images/slider/apartments.jpg',
      '/images/slider/houses.jpg',
      '/images/slider/commercial.jpg',
    ],
  },
  {
    id: 2,
    Propertytitle: 'Plot #1',
    coverImage: '/images/properties/PropertyCardImagePlots.jpeg',
    postedDate: '1 day ago',
    propertyData: {
      propertyPrice: '1.2 Crore',
      propertyDemand: '1 Crore 50 Lac',
      area: '1080 sq.ft',
      title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
      description:
        'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
      type: 'Plots',
      direction: 'East Open',
      location: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        city: 'Karachi',
      },
      amenities: [
        'Park',
        'Masjid',
        'Playground',
        '24 Hours CCTV Security System',
        '24 Hours Water Supply',
      ],
    },
    agentData: {
      id: 1,
      price: '1.5 Crore',
      profileimage: '/images/agent-profile/profileimage.svg',
      name: 'Arman Khan',
      agentDescription:
        'It was popularised in the 1960s with the release of Letraset sheets containing Lorem',
      profileLink: '/agents/1',
      chatLink: '/chat/agent/1',
    },
    propertyDetails: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
    sliderImages: [
      '/images/slider/apartments.jpg',
      '/images/slider/houses.jpg',
      '/images/slider/commercial.jpg',
    ],
  },
  {
    id: 3,
    Propertytitle: 'Comemrcial #1',
    coverImage: '/images/properties/PropertyCardImageCommercial.jpeg',
    postedDate: '1 day ago',
    propertyData: {
      propertyPrice: '1.2 Crore',
      propertyDemand: '1 Crore 50 Lac',
      area: '1080 sq.ft',
      title: 'Plot For sale Zeenatabad Society Scheme 33 Sector 19a',
      description:
        'Plot for sale in Zeenatabad Society, Scheme 33 Sector 19A, 120 Sqyd West open corner 24 Feet road (Leased). Corner Boundary Wall Society 150 Feet Road.',
      type: 'Commercial',
      direction: 'East Open',
      location: {
        address: 'Sector 31 - Punjabi Saudagar City Phase 2, Scheme 33',
        purpose: 'Sell',
        Type: 'House',
        city: 'Karachi',
      },
      amenities: [
        'Park',
        'Masjid',
        'Playground',
        '24 Hours CCTV Security System',
        '24 Hours Water Supply',
      ],
    },
    agentData: {
      id: 1,
      price: '1.5 Crore',
      profileimage: '/images/agent-profile/profileimage.svg',
      name: 'Arman Khan',
      agentDescription:
        'It was popularised in the 1960s with the release of Letraset sheets containing Lorem',
      profileLink: '/agents/1',
      chatLink: '/chat/agent/1',
    },
    propertyDetails: {
      type: 'Residential plot',
      location: 'Scheme 33,Karachi',
      price: '1.5 Crore',
      purpose: 'For Sale',
      bedroom: '03',
      bath: '05',
      parking: '02',
    },
    sliderImages: [
      '/images/slider/apartments.jpg',
      '/images/slider/houses.jpg',
      '/images/slider/commercial.jpg',
    ],
  },
];
export const PROPERTY_PURPOSE = {
  propertyPurpose: {
    locationAndPurpose: 'Location & Purpose',
    purpose: 'Purpose',
    propertyType: 'Property Type',
    city: 'City',
    location: 'Location',
  },
  propertyType: {
    house: 'House',
    plots: 'Plots',
    commercial: 'Commercial',
  },
};
export const PROPERTY_ESTATE = {
  propertyAttributes: [
    { label: 'Type' },
    { label: 'Location' },
    { label: 'Price' },
    { label: 'Purpose' },
    { label: 'Bedroom' },
    { label: 'Bath' },
    { label: 'Parking' },
  ],
  propertyDetails: {
    overview: 'Overview',
    title: 'Title',
    decription: 'Description',
    area: 'Area',
    amenities: 'Amenities',
    demand: 'Demand',
    reach: 'Reach out to us:',
    unit: 'PKR',
    message: 'Message',
  },
};

export const PROPERTY_DETAILS = {
  agentProfile: 'Agent Profile',
  viewMore: 'View More',
  posted: 'Posted',
  pkr: 'PKR',
  agent: '/project/',
  properties: '/project/',
  propertyDetals: 'Property Details',
};
