export const getAgentInitialFormValues = (updated, currentUser) => {
  return {
    property_id: updated?.property_id || '',
    user_id: currentUser?.id || '',
    status: `${updated?.status || ''}`,
    title: `${updated?.title || ''}`,
    location: `${updated?.location || ''}`,
    description: `${updated?.description || ''}`,
    area: `${updated?.area || ''}`,
    amount: `${updated?.amount || ''}`,
    areaUnit: `${updated?.areaUnit || ''}`,
    amountCurrency: `${updated?.amountCurrency || ''}`,
    city: `${updated?.city || ''}`,
    bedrooms: `${updated?.bedrooms || ''}`,
    connects: `${updated?.connects || ''}`,
    bathrooms: `${updated?.bathrooms || ''}`,
    parking: `${updated?.parking || ''}`,
    clubhouse: `${updated?.clubhouse || ''}`,
    swimming_pool: `${updated?.swimming_pool || ''}`,
    fitness_center: `${updated?.fitness_center || ''}`,
    playground: `${updated?.playground || ''}`,
    servant_area: `${updated?.servant_area || ''}`,
    utility_store: `${updated?.utility_store || ''}`,
    rooftop_terrace: `${updated?.rooftop_terrace || ''}`,
    on_site_maintenance: `${updated?.on_site_maintenance || ''}`,
    washing_area: `${updated?.washing_area || ''}`,
    hour_electricity: `${updated?.hour_electricity || ''}`,
    auto_generator: `${updated?.auto_generator || ''}`,
    complete_boundary_wall: `${updated?.complete_boundary_wall || ''}`,
    walking_trails: `${updated?.walking_trails || ''}`,
    pet_friendly_facilities: `${updated?.pet_friendly_facilities || ''}`,
    security: `${updated?.security || ''}`,
    masjid: `${updated?.masjid || ''}`,
    corridor: `${updated?.corridor || ''}`,
    r_o_plant: `${updated?.r_o_plant || ''}`,
    basketball_courts: `${updated?.basketball_courts || ''}`,
    huge_park: `${updated?.huge_park || ''}`,
    concierge_services: `${updated?.concierge_services || ''}`,
    business_centre: `${updated?.business_centre || ''}`,
    purpose: `${updated?.purpose || ''}`,
    propertyCategory: `${updated?.propertyCategory || ''}`,
    propertyType: `${updated?.propertyType || ''}`,
    instalmentAvailable: `${updated?.instalmentAvailable || ''}`,
    readyPossession: `${updated?.readyPossession || ''}`,
    images: updated?.images || [],
    videos: updated?.videos || [],
    created_at: new Date().toISOString(),
  };
};

export const getUserInitialFormValues = (updated, currentUser) => {
  return {
    property_id: updated?.property_id || '',
    user_id: currentUser?.id || '',
    status: `${updated?.status || ''}`,
    title: `${updated?.title || ''}`,
    location: `${updated?.location || ''}`,
    description: `${updated?.description || ''}`,
    area: `${updated?.area || ''}`,
    amount: `${updated?.amount || ''}`,
    areaUnit: `${updated?.areaUnit || ''}`,
    amountCurrency: `${updated?.amountCurrency || ''}`,
    city: `${updated?.city || ''}`,
    bedrooms: `${updated?.bedrooms || ''}`,
    connects: `${updated?.connects || ''}`,
    bathrooms: `${updated?.bathrooms || ''}`,
    parking: `${updated?.parking || ''}`,
    purpose: `${updated?.purpose || ''}`,
    propertyCategory: `${updated?.propertyCategory || ''}`,
    propertyType: `${updated?.propertyType || ''}`,
    instalmentAvailable: `${updated?.instalmentAvailable || ''}`,
    readyPossession: `${updated?.readyPossession || ''}`,
  };
};
