export const AGENT_PROFILE_FORM_DATA = {
  heading: 'Change Password',
  buttonText: 'Save changes',
  image: '/images/agent_form/agent_form_background.png',
  Profile: { name: 'Arman khan', email: 'armankhan@gmail.com' },
  fields: [
    {
      label: 'Full Name',
      name: 'first_name',
      value: 'ok',
      place: 'Enter First Name',
      type: 'text',
      helperText: 'First Name',
      width: { xs: '100%', sm: '100%', md: '100%', lg: '93%' },
      sizes: { xs: 12, sm: 12, md: 11.2, lg: 5 },
    },
    {
      label: '',
      name: 'last_name',
      value: '',
      place: 'Enter Last Name',
      type: 'text',
      helperText: 'Last Name',
      pt: { xs: 0, lg: '25px' },
      width: { xs: '100%', sm: '100%', md: '100%', lg: '93.6%' },
      sizes: { xs: 12, sm: 12, md: 11.2, lg: 5.3 },
    },
    {
      label: 'Email',
      name: 'email',
      value: '',
      place: '@gmail.com',
      type: 'email',
      helperText: '',
      width: { xs: '100%', sm: '100%', md: '100%', lg: '93%' },
      sizes: { xs: 12, sm: 12, md: 11.2, lg: 5 },
    },
    {
      label: 'Landline',
      name: 'landline_number',
      value: '',
      place: 'Enter Landline',
      type: 'number',
      helperText: '',
      width: { xs: '100%', sm: '100%', md: '100%', lg: '69%' },
      sizes: { xs: 12, sm: 12, md: 11.2, lg: 5 },
    },
    {
      label: 'Whatsapp',
      place: '',
      type: 'number',
      name: 'whatsapp',
      value: '',
      helperText: '',
      width: { xs: '100%', sm: '100%', md: '100%', lg: '69%' },
      dropdowns: [
        {
          icon: '/images/agent_form/pakistan_flag.png',
          code: '+92',
          label: 'Pakistan',
        },
        {
          icon: '/images/agent_form/indiaFlag.png',
          code: '+91',
          label: 'India',
        },
        {
          icon: '/images/agent_form/chinaFlag.png',
          code: '+42',
          label: 'china',
        },
        {
          icon: '/images/agent_form/australiaFlag.png',
          code: '+45',
          label: 'australia',
        },
      ],

      sizes: { xs: 12, sm: 12, md: 11.2, lg: 5 },
    },
    {
      label: 'Mobile',
      place: '',
      type: 'number',
      name: 'mobile_number',
      value: '',
      helperText: '',
      width: { xs: '100%', sm: '85%', md: '76%', lg: '56.2%' },
      dropdowns: [
        {
          icon: '/images/agent_form/pakistan_flag.png',
          code: '+92',
          label: 'Pakistan',
        },
        {
          icon: '/images/agent_form/indiaFlag.png',
          code: '+91',
          label: 'India',
        },
        {
          icon: '/images/agent_form/chinaFlag.png',
          code: '+42',
          label: 'china',
        },
        {
          icon: '/images/agent_form/australiaFlag.png',
          code: '+45',
          label: 'australia',
        },
      ],
      buttonText: 'Verify',
      sizes: { xs: 12, sm: 12, md: 11.2, lg: 6 },
    },
    {
      label: 'Country',
      name: 'country',
      value: '',
      place: 'Enter Country',
      type: 'text',
      helperText: '',
      width: { xs: '100%', sm: '100%', md: '100%', lg: '69%' },
      sizes: { xs: 12, sm: 12, md: 11.2, lg: 5 },
    },
    {
      label: 'City',
      name: 'city',
      value: '',
      place: 'Enter City',
      type: 'text',
      helperText: '',
      width: { xs: '100%', sm: '100%', md: '100%', lg: '69%' },
      sizes: { xs: 12, sm: 12, md: 11.2, lg: 5 },
    },
    {
      label: 'Address',
      name: 'address',
      value: '',
      place: 'Add Address',
      type: 'text',
      helperText: '',
      width: { xs: '100%', sm: '100%', md: '100%', lg: '100%', xl: '100%' },
      sizes: { xs: 12, sm: 12, md: 11.2, lg: 10 },
    },
    {
      id: 'outlined-multiline-static',
      label: 'Bio',
      name: 'about',
      value: '',
      place: 'Enter Bio',
      type: 'textArea',
      helperText: '',
      rows: '4',
      multiline: true,
      width: { xs: '100%', sm: '100%', md: '100%', lg: '100%' },
      sizes: { xs: 12, sm: 12, md: 11.2, lg: 10 },
    },
  ],
  passwordfields: [
    {
      label: 'Enter Old Password',
      name: 'oldPassword',
      value: '',
      place: 'Enter Old Password',
      type: 'password',
      helperText: '',
      width: { xs: '100%', sm: '100%', md: '100%', lg: '69%' },
      sizes: { xs: 12, sm: 12, md: 11.2, lg: 5 },
    },
    {
      label: 'Enter New Password',
      name: 'newPassword',
      value: '',
      place: 'Enter New Password',
      type: 'password',
      helperText: '',
      width: { xs: '100%', sm: '100%', md: '100%', lg: '69%' },
      sizes: { xs: 12, sm: 12, md: 11.2, lg: 5 },
    },
    {
      label: 'Confirm Password',
      name: 'confirmPassword',
      value: '',
      place: 'Confirm Password',
      type: 'password',
      helperText: '',
      width: { xs: '100%', sm: '100%', md: '100%', lg: '69%' },
      sizes: { xs: 12, sm: 12, md: 11.2, lg: 5 },
    },
  ],
  checkbox: {
    label: 'Logout from all other devices',
    name: 'checkbox',
    value: '',
    type: 'checkbox',
    helperText: '',
  },
};

export const PROFILE_INFO = {
  image: '/images/profile.png',
  title: 'Arman Khan',
  description: [
    {
      email: 'armanespark@gmail.com',
      alt: 'amenities',
      text: '',
      icon: '',
    },
  ],
};
