export const COVER_LETTER = {
  form: 'buyingSellingForm',
  addiotionalFeature:
    'Add additional features e.g. Rooftop terrace, 24/7 security, Walking trails, Washing area etc',
  addAmentiesLabel: 'Add Amenities',
  save: 'Save',
  cancel: 'Cancel',
  saveDraft: 'Save as draft',
  submitAd: 'Submit Ad',
  SubmitProposal: 'Submit Proposal',
  property: [
    {
      image: '/images/listing-page/home.svg',
      title: 'Listings Information',
    },
    {
      image: '/images/listing-page/Property.svg',
      title: 'Property Price',
    },
    {
      image: '/images/listing-page/Gallery.svg',
      title: 'Good Property Images',
    },
  ],
  IconTitle: [
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'House',
      label: 'houseBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Flat',
      label: 'flatBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Upper Portion',
      label: 'upperPortionBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Lower Portion',
      label: 'lowerPortionBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Farm House',
      label: 'farmHouseBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Room',
      label: 'roomBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Rent House',
      label: 'rentHouseBtn',
      value: '',
    },
  ],
  propertyPlot: [
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Residential Plots',
      label: 'residentialPlotsBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Commercial Plots',
      label: 'CommercialPlotsBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Agriculture Land',
      label: 'agricultureLandBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Industrail Land',
      label: 'industrailLandBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Plot File',
      label: 'plotFileBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Plot Form',
      label: 'plotFormBtn',
      value: '',
    },
  ],
  propertyCommercial: [
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Office',
      label: 'officeBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Shop',
      label: 'shopBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Ware house',
      label: 'wareHouseBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Building',
      label: 'buildingBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      title: 'Other...',
      label: 'otherBtn',
      value: '',
    },
  ],
  postTitles: {
    adInfo: 'Ad information',
    locationandpurpose: 'Location & Purpose',
    sizeprice: 'Property Size and Pricing',
    featureamenities: 'Features & Amenities',
    imagesvidoes: 'Property Images and Videos',
  },
  addInfo: [
    {
      image: '/images/listing-page/title.svg',
      text: 'Title',
      placeholder: 'Enter property title e.g. Beautiful House in DHA Phase 5',
      label: 'title',
      value: '',
    },
    {
      image: '/images/listing-page/description.svg',
      text: 'Description',
      placeholder: 'Describe your property, it’s features, area it is in etc.',
      label: 'description',
      value: '',
    },
  ],

  buy: [
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      text: 'Buy',
      label: 'sellBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      text: 'Rent',
      label: 'rentBtn',
      value: '',
    },
  ],
  sell: [
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      text: 'Sell',
      label: 'sellBtn',
      value: '',
    },
    {
      image: '/images/listing-page/house.svg',
      activeImage: '/images/listing-page/housesell.svg',
      text: 'Rent',
      label: 'rentBtn',
      value: '',
    },
  ],
  purpose: {
    images: '/images/listing-page/select.svg',
    text: 'Select Purpose',
  },
  propertyType: {
    images: '/images/listing-page/buildings.svg',
    text: 'Select Property Type',
  },

  city: {
    images: '/images/listing-page/pinlocation.svg',
    text: 'Select City',
  },
  location: {
    images: '/images/listing-page/location.svg',
    text: 'Select Location',
  },
  propertySize: [
    {
      image: '/images/listing-page/areasize.svg',
      text: 'Area Size',
      placeholder: 'Enter Unit',
      dropPlaceholder: 'Select Unit',
      label: 'area',
      value: '',
      unit: 'areaUnit',
    },
    {
      image: '/images/listing-page/amount.svg',
      text: 'Amount ',
      placeholder: 'Enter Amount',
      dropPlaceholder: 'PKR',
      label: 'amount',
      value: '',
      unit: 'amountCurrency',
    },
  ],

  selectCityOptions: [
    {
      label: 'Karachi',
      value: '',
    },
    {
      label: 'Lahore',
      value: '',
    },
  ],

  aeraSizes: ['sq.ft', 'sq.yd', 'sq.m', 'Marla', 'Kanal'],

  currency: ['PKR', 'CAD', 'SAR', 'AED', 'GBP', 'USD'],

  installment: [
    {
      image: '/images/listing-page/installment.svg',
      title: 'Instalment available ',
      description: 'Enable if listing is available on instalments',
      value: false,
      label: 'instalmentAvailable',
    },
    {
      image: '/images/listing-page/notepad.svg',
      title: 'Ready For Possession ',
      description: 'Enable if listing is ready for possession',
      value: false,
      label: 'readyPossession',
    },
  ],
  feature: [
    {
      image: '/images/listing-page/bed.svg',
      title: 'Bedrooms',
      name: 'bedrooms',
      limit: 20,
    },
    {
      image: '/images/listing-page/room.svg',
      title: 'Bathrooms',
      name: 'bathrooms',
      limit: 20,
    },
    {
      image: '/images/listing-page/parking.svg',
      title: 'Parking',
      name: 'parking',
      limit: 20,
    },
  ],
  upload: {
    images: '/images/listing-page/select.svg',
    text: 'Upload Images and video of your Property',
  },
  uploadButton: [
    {
      label: 'Upload Images',
      text: 'uploadImage',
      value: '',
    },
    {
      label: 'Upload Video ',
      text: 'uploadVideo',
      value: '',
    },
  ],
  uploadInstruction: [
    {
      image: '/images/listing-page/tick.svg',
      text: 'Cover all areas of your property',
    },
    {
      image: '/images/listing-page/tick.svg',
      text: 'Maximum 5 pictures and 5 videos can be uploaded',
    },
    {
      image: '/images/listing-page/tick.svg',
      text: 'Ads with picture got 5x more views and leads',
    },
    {
      image: '/images/listing-page/tick.svg',
      text: 'Upload good quality pictures with proper lighting',
    },
    {
      image: '/images/listing-page/tick.svg',
      text: 'The video upload feature is optional; you can choose to upload photos without including a video.',
    },
  ],
  addAmenities: [
    {
      id: 1,
      image: '/images/add-amenities/swimmingPool.svg',
      title: 'Swimming pool',
      name: 'swimming_pool',
    },
    {
      id: 2,
      image: '/images/add-amenities/washingArea.svg',
      title: 'Washing area',
      name: 'washing_area',
    },
    {
      id: 3,
      image: '/images/add-amenities/mosque.svg',
      title: 'Masjid',
      name: 'masjid',
    },
    {
      id: 4,
      image: '/images/add-amenities/fitnessCenter.svg',
      title: 'Fitness center',
      name: 'fitness_center',
    },
    {
      id: 5,
      image: '/images/add-amenities/electricity.svg',
      title: 'Hour Electricity',
      name: 'hour_electricity',
    },
    {
      id: 6,
      image: '/images/add-amenities/corridor.svg',
      title: 'Corridor',
      name: 'corridor',
    },
    {
      id: 7,
      image: '/images/add-amenities/clubHouse.svg',
      title: 'Clubhouse',
      name: 'clubhouse',
    },
    {
      id: 8,
      image: '/images/add-amenities/autoGenerator.svg',
      title: 'Auto Generator',
      name: 'auto_generator',
    },
    {
      id: 9,
      image: '/images/add-amenities/roPlant.svg',
      title: 'R.O Plant',
      name: 'r_o_plant',
    },
    {
      id: 10,
      image: '/images/add-amenities/playground.svg',
      title: 'Playground',
      name: 'playground',
    },
    {
      id: 11,
      image: '/images/add-amenities/boundaryWall.svg',
      title: 'Complete Boundary Wall',
      name: 'complete_boundary_wall',
    },
    {
      id: 12,
      image: '/images/add-amenities/basketballCourts.svg',
      title: 'Basketball courts',
      name: 'basketball_courts',
    },
    {
      id: 13,
      image: '/images/add-amenities/servantArea.svg',
      title: 'Servant Area',
      name: 'servant_area',
    },
    {
      id: 15,
      image: '/images/add-amenities/hugePark.svg',
      title: 'Huge Park',
      name: 'huge_park',
    },
    {
      id: 16,
      image: '/images/add-amenities/utilityStore.svg',
      title: 'Utility Store',
      name: 'utility_store',
    },
    {
      id: 17,
      image: '/images/add-amenities/walkingTrails.svg',
      title: 'Walking trails',
      name: 'walking_trails',
    },
    {
      id: 18,
      image: '/images/add-amenities/services.svg',
      title: 'Concierge services',
      name: 'concierge_services',
    },
    {
      id: 19,
      image: '/images/add-amenities/rooftopTerrace.svg',
      title: 'Rooftop terrace',
      name: 'rooftop_terrace',
    },
    {
      id: 20,
      image: '/images/add-amenities/petfriendlyFacilities.svg',
      title: 'Pet-friendly facilities',
      name: 'pet_friendly_facilities',
    },
    {
      id: 21,
      image: '/images/add-amenities/businessCenter.svg',
      title: 'Business centre',
      name: 'business_centre',
    },
    {
      id: 22,
      image: '/images/add-amenities/maintenance.svg',
      title: 'On-site maintenance',
      name: 'on_site_maintenance',
    },
    {
      id: 23,
      image: '/images/add-amenities/securityCamera.svg',
      title: '24/7 security',
      name: 'security',
    },
  ],
};

export const COVER_LETTER_VALUES = {
  property_id: '',
  agent_id: '',
  status: '',
  title: '',
  location: '',
  proposal_id: '',
  description: '',
  area: '',
  amount: '',
  areaUnit: '',
  amountCurrency: '',
  city: '',
  bedrooms: 0,
  connects: '',
  bathrooms: 0,
  parking: 0,
  clubhouse: 0,
  swimming_pool: 0,
  fitness_center: 0,
  playground: 0,
  servant_area: 0,
  utility_store: 0,
  rooftop_terrace: 0,
  on_site_maintenance: 0,
  washing_area: 0,
  hour_electricity: 0,
  auto_generator: 0,
  complete_boundary_wall: 0,
  walking_trails: 0,
  pet_friendly_facilities: 0,
  security: 0,
  masjid: 0,
  corridor: 0,
  r_o_plant: 0,
  basketball_courts: 0,
  huge_park: 0,
  concierge_services: 0,
  business_centre: 0,
  other_features: [],
  purpose: 'Sell',
  propertyCategory: 'House',
  propertyType: 'Sell',
  images: [],
  videos: [],
  created_at: '',
  instalmentAvailable: false,
  readyPossession: false,
};
