export const ORDER_HISTORY = {
  tableHead: ['Ordered by', 'Description', 'Time', 'Date', 'Total'],
  tableData: [
    {
      id: 1,
      name: 'Arman Khan',
      description: 'Basic Package + 90 connects  ',
      time: '09:22 PM',
      date: '01-02-2024',
      total: 'Rs. 3500',
    },
    {
      id: 2,
      name: 'Arman Khan',
      description: 'Basic Package + 90 connects',
      time: '09:22 PM',
      date: '01-02-2024',
      total: 'Rs. 3500',
    },
    {
      id: 3,
      name: 'Arman Khan',
      description: 'Basic Package + 90 connects',
      time: '09:22 PM',
      date: '01-02-2024',
      total: 'Rs. 3500',
    },
    {
      id: 4,
      name: 'Arman Khan',
      description: 'Basic Package + 90 connects',
      time: '09:22 PM',
      date: '01-02-2024',
      total: 'Rs. 3500',
    },
    {
      id: 5,
      name: 'Arman Khan',
      description: 'Basic Package + 90 connects',
      time: '09:22 PM',
      date: '01-02-2024',
      total: 'Rs. 3500',
    },
    {
      id: 6,
      name: 'Arman Khan',
      description: 'Basic Package + 90 connects',
      time: '09:22 PM',
      date: '01-02-2024',
      total: 'Rs. 3500',
    },
  ],
  space: Array(5).fill({ space: '' }),
  title: 'Order History',
};
