export const PROJECTS_DATA = [
  {
    id: 1,
    propertyCategory: 'category_1',
    images: [],
    amountCurrency: 'USD',
    amount: 10000,
    location: 'Location 1',
    area: 200,
    areaUnit: 'sqft',
    orientation: 'Orientation 1',
    description: 'Description of project 1',
  },
  {
    id: 2,
    propertyCategory: 'category_2',
    images: [],
    amountCurrency: 'EUR',
    amount: 15000,
    location: 'Location 2',
    area: 300,
    areaUnit: 'sqft',
    orientation: 'Orientation 2',
    description: 'Description of project 2',
  },
  {
    id: 3,
    propertyCategory: 'category_1',
    images: [],
    amountCurrency: 'USD',
    amount: 12000,
    location: 'Location 3',
    area: 250,
    areaUnit: 'sqft',
    orientation: 'Orientation 3',
    description: 'Description of project 3',
  },
  {
    id: 4,
    propertyCategory: 'category_1',
    images: [],
    amountCurrency: 'USD',
    amount: 10000,
    location: 'Location 1',
    area: 200,
    areaUnit: 'sqft',
    orientation: 'Orientation 1',
    description: 'Description of project 1',
  },
  {
    id: 5,
    propertyCategory: 'category_2',
    images: [],
    amountCurrency: 'EUR',
    amount: 15000,
    location: 'Location 2',
    area: 300,
    areaUnit: 'sqft',
    orientation: 'Orientation 2',
    description: 'Description of project 2',
  },
  {
    id: 6,
    propertyCategory: 'category_1',
    images: [],
    amountCurrency: 'USD',
    amount: 12000,
    location: 'Location 3',
    area: 250,
    areaUnit: 'sqft',
    orientation: 'Orientation 3',
    description: 'Description of project 3',
  },
  {
    id: 7,
    propertyCategory: 'category_1',
    images: [],
    amountCurrency: 'USD',
    amount: 10000,
    location: 'Location 1',
    area: 200,
    areaUnit: 'sqft',
    orientation: 'Orientation 1',
    description: 'Description of project 1',
  },
  {
    id: 8,
    propertyCategory: 'category_2',
    images: [],
    amountCurrency: 'EUR',
    amount: 15000,
    location: 'Location 2',
    area: 300,
    areaUnit: 'sqft',
    orientation: 'Orientation 2',
    description: 'Description of project 2',
  },
  {
    id: 9,
    propertyCategory: 'category_1',
    images: [],
    amountCurrency: 'USD',
    amount: 12000,
    location: 'Location 3',
    area: 250,
    areaUnit: 'sqft',
    orientation: 'Orientation 3',
    description: 'Description of project 3',
  },
];
