export const AREA_UNITS = [
  { value: 'sqft', title: 'Sq.ft' },
  { value: 'sqm', title: 'Sq.M' },
  { value: 'sqyd', title: 'Sq.Yd' },
  { value: 'marla', title: 'Marla' },
  { value: 'kanal', title: 'Kanal' },
];
export const CURRENCY_UNITS = [
  { value: 'PKR', title: 'PKR' },
  { value: 'USD', title: 'USD' },
  { value: 'GBP', title: 'GBP' },
  { value: 'CAD', title: 'CAD' },
  { value: 'EUR', title: 'Euro' },
];
export const PROPERTY_TYPES = [
  { value: ' ', title: 'Any' },
  { value: 'sell', title: 'Sell' },
  { value: 'rent', title: 'Rent' },
];
export const PROPERTY_TABS_DATA = [
  {
    id: 1,
    label: 'Houses',
    value: 'houses',
    content: [
      {
        id: 1,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'All ',
        value: '',
      },
      {
        id: 2,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'House',
        value: 'house',
      },
      {
        id: 3,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Flat',
        value: 'flat',
      },
      {
        id: 4,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Upper Portion',
        value: 'upper-portion',
      },
      {
        id: 5,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Lower Portion',
        value: 'lower-portion',
      },
      {
        id: 6,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Farm House',
        value: 'farm-house',
      },
      {
        id: 7,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Room',
        value: 'room',
      },
      {
        id: 8,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Penthouse',
        value: 'penthouse',
      },
    ],
  },
  {
    id: 2,
    label: 'Plots',
    value: 'plots',
    content: [
      {
        id: 1,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'All ',
        value: '',
      },
      {
        id: 2,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Residential Plots',
        value: 'residential-plots',
      },
      {
        id: 3,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Commercial Plots',
        value: 'commercial-plots',
      },
      {
        id: 4,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Agriculture Land',
        value: 'agriculture-land',
      },
      {
        id: 5,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Industrail Land',
        value: 'industrail-land',
      },
      {
        id: 6,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Plot File',
        value: 'plot-file',
      },
      {
        id: 7,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Plot Form',
        value: 'plot-form',
      },
    ],
  },
  {
    id: 3,
    label: 'Commercials',
    value: 'commercials',
    content: [
      {
        id: 1,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'All ',
        value: '',
      },
      {
        id: 2,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Office',
        value: 'office',
      },
      {
        id: 3,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Shop',
        value: 'shop',
      },
      {
        id: 4,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Ware house',
        value: 'ware-house',
      },
      {
        id: 5,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Building',
        value: 'building',
      },
      {
        id: 6,
        image: '/images/listing-page/house.svg',
        activeImage: '/images/listing-page/housesell.svg',
        title: 'Other...',
        value: 'other',
      },
    ],
  },
];
export const CITIES_NAME = [
  { id: 1, value: 'karachi', title: 'Karachi' },
  { id: 2, value: 'lahore', title: 'Lahore' },
  { id: 3, value: 'faisalabad', title: 'Faisalabad' },
  { id: 4, value: 'rawalpindi', title: 'Rawalpindi' },
  { id: 5, value: 'multan', title: 'Multan' },
  { id: 6, value: 'gujranwala', title: 'Gujranwala' },
  { id: 7, value: 'hyderabad', title: 'Hyderabad' },
  { id: 8, value: 'peshawar', title: 'Peshawar' },
  { id: 9, value: 'islamabad', title: 'Islamabad' },
  { id: 10, value: 'quetta', title: 'Quetta' },
  { id: 11, value: 'sargodha', title: 'Sargodha' },
  { id: 12, value: 'sialkot', title: 'Sialkot' },
  { id: 13, value: 'bahawalpur', title: 'Bahawalpur' },
  { id: 14, value: 'sukkur', title: 'Sukkur' },
  { id: 15, value: 'kandhkot', title: 'Kandhkot' },
  { id: 16, value: 'sheikhupura', title: 'Sheikhupura' },
  { id: 17, value: 'mardan', title: 'Mardan' },
  { id: 18, value: 'gujrat', title: 'Gujrat' },
  { id: 19, value: 'larkana', title: 'Larkana' },
  { id: 20, value: 'kasur', title: 'Kasur' },
  { id: 21, value: 'rahim-yar-khan', title: 'Rahim Yar Khan' },
  { id: 22, value: 'sahiwal', title: 'Sahiwal' },
  { id: 23, value: 'okara', title: 'Okara' },
  { id: 24, value: 'wah-cantonment', title: 'Wah Cantonment' },
  { id: 25, value: 'dera-ghazi-khan', title: 'Dera Ghazi Khan' },
  { id: 26, value: 'mingora', title: 'Mingora' },
  { id: 27, value: 'mirpur-khas', title: 'Mirpur Khas' },
  { id: 28, value: 'chiniot', title: 'Chiniot' },
  { id: 29, value: 'nawabshah', title: 'Nawabshah' },
  { id: 30, value: 'kamoke', title: 'Kamoke' },
  { id: 31, value: 'burewala', title: 'Burewala' },
  { id: 32, value: 'jhelum', title: 'Jhelum' },
  { id: 33, value: 'sadiqabad', title: 'Sadiqabad' },
  { id: 34, value: 'khanewal', title: 'Khanewal' },
  { id: 35, value: 'hafizabad', title: 'Hafizabad' },
  { id: 36, value: 'kohat', title: 'Kohat' },
  { id: 37, value: 'jacobabad', title: 'Jacobabad' },
  { id: 38, value: 'shikarpur', title: 'Shikarpur' },
  { id: 39, value: 'muzaffargarh', title: 'Muzaffargarh' },
  { id: 40, value: 'khanpur', title: 'Khanpur' },
  { id: 41, value: 'gojra', title: 'Gojra' },
  { id: 42, value: 'bahawalnagar', title: 'Bahawalnagar' },
  { id: 43, value: 'abbottabad', title: 'Abbottabad' },
  { id: 44, value: 'muridke', title: 'Muridke' },
  { id: 45, value: 'pakpattan', title: 'Pakpattan' },
  { id: 46, value: 'khuzdar', title: 'Khuzdar' },
  { id: 47, value: 'jaranwala', title: 'Jaranwala' },
  { id: 48, value: 'chishtian', title: 'Chishtian' },
  { id: 49, value: 'daska', title: 'Daska' },
  { id: 50, value: 'mandi-bahauddin', title: 'Mandi Bahauddin' },
  { id: 51, value: 'ahmadpur-east', title: 'Ahmadpur East' },
  { id: 52, value: 'kamalia', title: 'Kamalia' },
  { id: 53, value: 'tando-adam', title: 'Tando Adam' },
  { id: 54, value: 'khairpur', title: 'Khairpur' },
  { id: 55, value: 'dera-ismail-khan', title: 'Dera Ismail Khan' },
  { id: 56, value: 'vehari', title: 'Vehari' },
  { id: 57, value: 'nowshera', title: 'Nowshera' },
  { id: 58, value: 'dadu', title: 'Dadu' },
  { id: 59, value: 'wazirabad', title: 'Wazirabad' },
  { id: 60, value: 'khushab', title: 'Khushab' },
  { id: 61, value: 'charsada', title: 'Charsada' },
  { id: 62, value: 'swabi', title: 'Swabi' },
  { id: 63, value: 'chakwal', title: 'Chakwal' },
  { id: 64, value: 'mianwali', title: 'Mianwali' },
  { id: 65, value: 'tando-allahyar', title: 'Tando Allahyar' },
  { id: 66, value: 'kot-adu', title: 'Kot Adu' },
  { id: 67, value: 'farooka', title: 'Farooka' },
  { id: 68, value: 'chichawatni', title: 'Chichawatni' },
  { id: 69, value: 'vehari', title: 'Vehari' },
  { id: 70, value: 'mansehra', title: 'Mansehra' },
];

export const AMENITIES_NAME = [
  {
    id: 1,
    image: '/images/add-amenities/swimmingPool.svg',
    title: 'Swimming pool',
  },
  {
    id: 2,
    image: '/images/add-amenities/washingArea.svg',
    title: 'Washing area',
  },
  {
    id: 3,
    image: '/images/add-amenities/mosque.svg',
    title: 'Masjid',
  },
  {
    id: 4,
    image: '/images/add-amenities/fitnessCenter.svg',
    title: 'Fitness center',
  },
  {
    id: 5,
    image: '/images/add-amenities/electricity.svg',
    title: 'Hour Electricity',
  },
  {
    id: 6,
    image: '/images/add-amenities/corridor.svg',
    title: 'Corridor',
  },
  {
    id: 7,
    image: '/images/add-amenities/clubHouse.svg',
    title: 'Clubhouse',
  },
  {
    id: 8,
    image: '/images/add-amenities/autoGenerator.svg',
    title: 'Auto Generator',
  },
  {
    id: 9,
    image: '/images/add-amenities/roPlant.svg',
    title: 'R.O Plant',
  },
  {
    id: 10,
    image: '/images/add-amenities/playground.svg',
    title: 'Playground',
  },
  {
    id: 11,
    image: '/images/add-amenities/boundaryWall.svg',
    title: 'Complete Boundary Wall',
  },
  {
    id: 12,
    image: '/images/add-amenities/basketballCourts.svg',
    title: 'Basketball courts',
  },
  {
    id: 13,
    image: '/images/add-amenities/servantArea.svg',
    title: 'Servant Area',
  },
  {
    id: 14,
    image: '/images/add-amenities/basketballCourts.svg',
    title: 'Basketball courts',
  },
  {
    id: 15,
    image: '/images/add-amenities/hugePark.svg',
    title: 'Huge Park',
  },
  {
    id: 16,
    image: '/images/add-amenities/utilityStore.svg',
    title: 'Utility Store',
  },
  {
    id: 17,
    image: '/images/add-amenities/walkingTrails.svg',
    title: 'Walking trails',
  },
  {
    id: 18,
    image: '/images/add-amenities/services.svg',
    title: 'Concierge services',
  },
  {
    id: 19,
    image: '/images/add-amenities/rooftopTerrace.svg',
    title: 'Rooftop terrace',
  },
  {
    id: 20,
    image: '/images/add-amenities/petfriendlyFacilities.svg',
    title: 'Pet-friendly facilities',
  },
  {
    id: 21,
    image: '/images/add-amenities/businessCenter.svg',
    title: 'Business centre',
  },
  {
    id: 22,
    image: '/images/add-amenities/maintenance.svg',
    title: 'On-site maintenance',
  },
  {
    id: 23,
    image: '/images/add-amenities/securityCamera.svg',
    title: '24/7 security',
  },
];
